language: csharp
mono: latest
dotnet: 1.0.0-preview2-1-003177

sudo: required
dist: trusty

os:
  - linux
  - osx
osx_image: xcode7.3

script:
- ./build.sh --verbosity diagnostic
  
notifications:
  email: false