language: csharp
mono: latest
dotnet: 1.0.0-preview2-1-003177

sudo: required
dist: trusty

os:
  - linux
  - osx
osx_image: xcode7.3

before_install:
- git fetch --unshallow --tags
- if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi

script:
  - cd CI
  - ./build.sh --verbosity diagnostic
  
notifications:
  email: false